services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studiodocpro-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run db:migrate && node server.js"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: studiodocpro-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: studiodocpro-postgres-data