version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # ✅ Dummy URL during build (so Next.js can compile even without DB)
        DATABASE_URL: postgresql://placeholder:placeholder@placeholder:5432/placeholder
    container_name: studiodocpro-app
    ports:
      - "9002:3000" # ✅ Expose app's internal port 3000 to host 9002
    environment:
      # ✅ Real DB URL used at runtime
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npm run db:migrate && npm start"
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: studiodocpro-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    name: studiodocpro-postgres-data
